# Generated by Django 4.2.6 on 2023-10-28 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/feedback/client')),
                ('source', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
