# Generated by Django 4.2.6 on 2023-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'FEEDBACK'},
        ),
    ]
