# Generated by Django 4.2.6 on 2023-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_created_at_alter_blogs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
