# Generated by Django 4.1.6 on 2023-11-07 09:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
