# Generated by Django 4.1.6 on 2023-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.CharField(max_length=10)),
                ('completed_project', models.CharField(max_length=10)),
                ('happy_customer', models.CharField(max_length=10)),
                ('working_hour', models.CharField(max_length=10)),
            ],
        ),
    ]
