# Generated by Django 4.1.6 on 2023-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='completed_project',
            field=models.CharField(max_length=10, verbose_name='Order Complete'),
        ),
    ]
