# Generated by Django 4.2.6 on 2023-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreskill',
            options={'verbose_name_plural': 'CORE SKILL'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name_plural': 'RESUME LINK'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'LANGUAGE'},
        ),
        migrations.AlterModelOptions(
            name='otherskill',
            options={'verbose_name_plural': 'OTHER SKILL'},
        ),
    ]
